### ISSUE TITLE
Broken link in repo description

### ISSUE THREAD

**Issue by AB1908** [afshinea/stanford-cs-229-machine-learning#14]
The link in the repo description (the one just under the repo title) is broken. It should point to https://stanford.edu/~shervine/teaching/cs-229/ instead of https://stanford.edu/~shervine/teaching/cs-229.html which 404s at the time of opening this issue. Would save a quick Google search in the future.

**Comment by MonicaStettler** [comment]
Please unsubscribe me. Thanks!

Monica 

    On Wednesday, January 16, 2019, 2:41:41 AM CST, Abhishek Bhattacherjee <notifications@github.com> wrote:  
 
 
The link in the repo description (the one just under the repo title) is broken. It should point to https://stanford.edu/~shervine/teaching/cs-229/ instead of https://stanford.edu/~shervine/teaching/cs-229.html which 404s at the time of opening this issue. Would save a quick Google search in the future.

**Comment by afshinea** [comment]
Great catch, thanks @AB1908! Now fixed.

**Comment by AB1908** [comment]
@MonicaStettler : You were never subscribed to this issue. Perhaps you should remove yourself from the *Watching* list to not receive updates. Hope that helps.

**Comment by MonicaStettler** [comment]
Thank you. I'll try that.

Monica

On Jan 16, 2019, at 11:02 PM, Abhishek Bhattacherjee <notifications@github.com> wrote:

@MonicaStettler : You were never subscribed to this issue. Perhaps you should remove yourself from the Watching list to not receive updates. Hope that helps.
