### ISSUE TITLE
Chinese version link

### ISSUE THREAD

**Issue by zhyongquan** [afshinea/stanford-cs-229-machine-learning#6]
can you add a link to https://github.com/MLEveryday/Machine-Learning-Cheatsheets?
we already finished the first three parts.

**Comment by shervinea** [comment]
Thanks for your message @zhyongquan. As responded [in this other issue](https://github.com/shervinea/cheatsheet-translation/issues/17), we would need these translations to be in the right format in order to be valid. 

Could you please fill [the fields of the Chinese folder](https://github.com/shervinea/cheatsheet-translation/tree/master/zh) accordingly and open a pull request for each of these cheatsheets? Thanks!
